In [51]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
import matplotlib.pyplot as plt
import random as r
import MetroSim as met
from matplotlib.animation import FuncAnimation
import os

In [224]:
J = 1
k = 1
def funcArray(steps, size, Temp): # Function to run through
    latt = met.Setup(size) # Set up random lattice of size^2
    ar = []
    ar.append(latt)
    s = 0
    while s < steps:
        n, m = r.randrange(0, size, 1), r.randrange(0, size, 1) # two random values for a random location on the lattice
        old  = (latt[(n-1)%size,m]*latt[n,m]) + (latt[(n+1)%size,m]*latt[n,m]) + (latt[n,(m-1)%size]*latt[n,m]) + (latt[n,(m+1)%size]*latt[n,m])
        latt[n,m] *= -1 # try flipping the spin at that site
        new  = (latt[(n-1)%size,m]*latt[n,m]) + (latt[(n+1)%size,m]*latt[n,m]) + (latt[n,(m-1)%size]*latt[n,m]) + (latt[n,(m+1)%size]*latt[n,m])
        de = -J*(new - old) # dE = Ef - Ei
        if de > 0 and r.random() > np.exp(-de/(k*Temp)):
            latt[n,m] *= -1 # Return the spin to normal if not accepted
        # The lattice wont change back unless the de is positive and the random number is above transition prob
        
        ar.append(latt)
        s += 1
        
    return ar, latt

In [225]:
h, j= funcArray(1000, 10, 1.0)

In [226]:
print(h[0])
print(j)
#print(h[999].flatten())

[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1 -1 -1]
 [ 1  1  1  1  1  1  1  1  1  1]]
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1 -1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [ 1  1  1  1  1  1  1  1 -1 -1]
 [ 1  1  1  1  1  1  1  1  1  1]]


In [53]:
latt = met.func(10, 16, 1.0)
print(latt)


[[ 1 -1 -1  1  1 -1  1 -1  1 -1  1  1 -1 -1  1 -1]
 [ 1 -1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1]
 [ 1  1 -1  1 -1  1 -1  1 -1  1  1  1 -1  1 -1 -1]
 [ 1  1  1  1  1  1 -1  1 -1  1  1  1  1 -1  1 -1]
 [-1  1 -1  1  1 -1 -1  1 -1 -1  1  1  1  1 -1 -1]
 [-1  1 -1  1  1 -1  1  1 -1 -1 -1  1 -1  1 -1  1]
 [-1  1 -1  1 -1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1]
 [-1  1  1  1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1]
 [-1 -1 -1 -1 -1 -1  1 -1 -1  1  1 -1  1 -1 -1 -1]
 [ 1 -1  1  1 -1 -1  1 -1 -1 -1  1  1 -1 -1 -1  1]
 [-1  1 -1 -1 -1 -1 -1 -1  1 -1 -1  1 -1 -1  1  1]
 [-1 -1  1 -1 -1  1  1 -1  1  1  1 -1  1  1  1  1]
 [ 1 -1 -1 -1 -1  1  1  1  1 -1  1 -1  1  1 -1 -1]
 [ 1 -1 -1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  1 -1]
 [-1  1 -1  1  1  1  1  1  1 -1 -1  1  1  1 -1  1]
 [ 1 -1  1  1 -1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1]]


In [57]:
y = latt.flatten()
print(y)

[ 1 -1 -1  1  1 -1  1 -1  1 -1  1  1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1  1
  1  1 -1 -1 -1 -1 -1 -1  1  1 -1  1 -1  1 -1  1 -1  1  1  1 -1  1 -1 -1
  1  1  1  1  1  1 -1  1 -1  1  1  1  1 -1  1 -1 -1  1 -1  1  1 -1 -1  1
 -1 -1  1  1  1  1 -1 -1 -1  1 -1  1  1 -1  1  1 -1 -1 -1  1 -1  1 -1  1
 -1  1 -1  1 -1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1  1  1  1 -1 -1 -1  1
 -1  1  1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1  1  1 -1  1 -1 -1 -1
  1 -1  1  1 -1 -1  1 -1 -1 -1  1  1 -1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1
  1 -1 -1  1 -1 -1  1  1 -1 -1  1 -1 -1  1  1 -1  1  1  1 -1  1  1  1  1
  1 -1 -1 -1 -1  1  1  1  1 -1  1 -1  1  1 -1 -1  1 -1 -1  1 -1  1  1  1
 -1 -1 -1 -1 -1 -1  1 -1 -1  1 -1  1  1  1  1  1  1 -1 -1  1  1  1 -1  1
  1 -1  1  1 -1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1]


In [58]:
l = y.reshape(16,16)
print(l)

[[ 1 -1 -1  1  1 -1  1 -1  1 -1  1  1 -1 -1  1 -1]
 [ 1 -1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1 -1 -1 -1]
 [ 1  1 -1  1 -1  1 -1  1 -1  1  1  1 -1  1 -1 -1]
 [ 1  1  1  1  1  1 -1  1 -1  1  1  1  1 -1  1 -1]
 [-1  1 -1  1  1 -1 -1  1 -1 -1  1  1  1  1 -1 -1]
 [-1  1 -1  1  1 -1  1  1 -1 -1 -1  1 -1  1 -1  1]
 [-1  1 -1  1 -1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1]
 [-1  1  1  1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1]
 [-1 -1 -1 -1 -1 -1  1 -1 -1  1  1 -1  1 -1 -1 -1]
 [ 1 -1  1  1 -1 -1  1 -1 -1 -1  1  1 -1 -1 -1  1]
 [-1  1 -1 -1 -1 -1 -1 -1  1 -1 -1  1 -1 -1  1  1]
 [-1 -1  1 -1 -1  1  1 -1  1  1  1 -1  1  1  1  1]
 [ 1 -1 -1 -1 -1  1  1  1  1 -1  1 -1  1  1 -1 -1]
 [ 1 -1 -1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  1 -1]
 [-1  1 -1  1  1  1  1  1  1 -1 -1  1  1  1 -1  1]
 [ 1 -1  1  1 -1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1]]


In [62]:
# Preparing the training and test data
# Must be normalized
data = pd.read_csv('16_25000_2800.csv') # Download a premade data set
# randomizing the data with the temperature index
randomized = np.random.permutation(data)
r= [i[1:] for i in randomized] 
name = [i[0] for i in randomized]

#

In [68]:
train_images = [i.reshape(16,16) for i in r[:10]]
print(train_images)

[array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.